# Generated by Django 5.1.3 on 2024-11-23 13:02

import django.db.models.deletion
import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuilderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('website', models.URLField(blank=True)),
                ('logo', models.FileField(blank=True, upload_to='')),
                ('company_name', models.CharField(max_length=200)),
                ('license_number', models.CharField(max_length=50)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('details', models.TextField(blank=True)),
            ],
            bases=(projects.models.SlugMixin, models.Model),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            bases=(projects.models.SlugMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(max_length=100)),
                ('plan_name', models.CharField(max_length=100)),
                ('plan', models.FileField(upload_to='')),
                ('availability_status', models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], default='Available', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=2)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            bases=(projects.models.SlugMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('testimonial', models.TextField()),
                ('image', models.FileField(upload_to='')),
                ('source', models.CharField(choices=[('Google', 'Google'), ('Facebook', 'Facebook'), ('Yelp', 'Yelp'), ('Zillow', 'Zillow'), ('Other', 'Other')], default='Other', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('community_title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('community_description', models.TextField(blank=True)),
                ('incentive_description', models.TextField(blank=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.city')),
                ('faqs', models.ManyToManyField(blank=True, to='projects.faq')),
                ('images', models.ManyToManyField(blank=True, to='projects.image')),
            ],
            bases=(projects.models.SlugMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('project_type', models.CharField(choices=[('Single Family', 'Single Family'), ('Multi Family', 'Multi Family'), ('Condominium', 'Condominium'), ('Townhouse', 'Townhouse'), ('Move in Ready', 'Move in Ready'), ('Other', 'Other')], default='Single Family', max_length=100)),
                ('status', models.CharField(choices=[('Planning', 'Planning Phase'), ('Approval', 'Approval Process'), ('Sales', 'Sales Phase'), ('Construction', 'Construction Phase'), ('Completed', 'Completed'), ('On Hold', 'On Hold')], default='Planning', max_length=100)),
                ('project_address', models.CharField(max_length=200)),
                ('price_starting_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_ending_at', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('project_description', models.TextField(blank=True)),
                ('project_video_url', models.URLField(blank=True)),
                ('area_square_footage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lot_size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('garage_spaces', models.IntegerField(blank=True, null=True)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.community')),
                ('documents', models.ManyToManyField(blank=True, to='projects.document')),
                ('images', models.ManyToManyField(blank=True, to='projects.image')),
                ('plans', models.ManyToManyField(blank=True, to='projects.plan')),
            ],
            bases=(projects.models.SlugMixin, models.Model),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.state'),
        ),
    ]
