# Generated by Django 5.1.3 on 2024-11-24 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_file_document_document_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='community',
        ),
        migrations.DeleteModel(
            name='Community',
        ),
    ]
