# Generated by Django 5.1.3 on 2025-07-30 04:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_developer_project_developer'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the floor plan', max_length=200)),
                ('house_type', models.CharField(choices=[('Single Family', 'Single Family'), ('Townhouse', 'Townhouse'), ('Duplex', 'Duplex'), ('Triplex', 'Triplex'), ('Condo', 'Condo'), ('Custom', 'Custom')], default='Single Family', max_length=50)),
                ('square_footage', models.PositiveIntegerField(help_text='Total square footage')),
                ('bedrooms', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('garage_spaces', models.PositiveIntegerField(default=0, help_text='Number of garage spaces')),
                ('availability_status', models.CharField(choices=[('Available', 'Available'), ('Reserved', 'Reserved'), ('Sold', 'Sold'), ('Coming Soon', 'Coming Soon')], default='Available', max_length=20)),
                ('starting_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('plan_image', models.FileField(blank=True, upload_to='floor_plans/')),
                ('plan_pdf', models.FileField(blank=True, upload_to='floor_plans/')),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Floor Plans',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(help_text='e.g., 112, 12A, 15B', max_length=50)),
                ('availability_status', models.CharField(choices=[('Available', 'Available'), ('Reserved', 'Reserved'), ('Sold', 'Sold'), ('Coming Soon', 'Coming Soon')], default='Available', max_length=20)),
                ('lot_size', models.DecimalField(blank=True, decimal_places=2, help_text='Lot size in square feet', max_digits=10, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Lots',
                'ordering': ['lot_number'],
            },
        ),
        migrations.CreateModel(
            name='Rendering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Kitchen, Living Room, Exterior', max_length=200)),
                ('image', models.FileField(upload_to='renderings/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Renderings',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SitePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(help_text='Overall site plan image', upload_to='site_plans/')),
                ('pdf', models.FileField(blank=True, help_text='PDF version of site plan', upload_to='site_plans/')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Site Plans',
            },
        ),
        migrations.DeleteModel(
            name='BuilderDetails',
        ),
        migrations.DeleteModel(
            name='FAQ',
        ),
        migrations.RemoveField(
            model_name='project',
            name='images',
        ),
        migrations.RemoveField(
            model_name='project',
            name='plans',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['state__name', 'name'], 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='developer',
            options={'ordering': ['name'], 'verbose_name_plural': 'Developers'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['name'], 'verbose_name_plural': 'States'},
        ),
        migrations.RenameField(
            model_name='developer',
            old_name='email',
            new_name='contact_email',
        ),
        migrations.RenameField(
            model_name='developer',
            old_name='phone',
            new_name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='document',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='document',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='documents',
        ),
        migrations.AddField(
            model_name='city',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='company_name',
            field=models.CharField(default='sdc', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='developer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='license_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('Brochure', 'Brochure'), ('Fact Sheet', 'Fact Sheet'), ('Floor Plan', 'Floor Plan'), ('Site Plan', 'Site Plan'), ('Contract', 'Contract'), ('Disclosure', 'Disclosure'), ('Permit', 'Permit'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='aps',
            field=models.TextField(blank=True, help_text='APS (Agreement of Purchase and Sale) details'),
        ),
        migrations.AddField(
            model_name='project',
            name='commission',
            field=models.TextField(blank=True, help_text='Rich text field for commission information'),
        ),
        migrations.AddField(
            model_name='project',
            name='deposit_structure',
            field=models.TextField(blank=True, help_text='Rich text field for deposit structure details'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='occupancy',
            field=models.TextField(blank=True, help_text='Occupancy timeline and details'),
        ),
        migrations.AddField(
            model_name='project',
            name='pricing_details',
            field=models.TextField(blank=True, help_text='Rich text field for detailed pricing information'),
        ),
        migrations.AddField(
            model_name='state',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='projects.state'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='bathrooms',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.city'),
        ),
        migrations.AlterField(
            model_name='project',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.developer'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='price_ending_at',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='price_starting_from',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('Single Family', 'Single Family'), ('Multi Family', 'Multi Family'), ('Condominium', 'Condominium'), ('Townhouse', 'Townhouse'), ('Move in Ready', 'Move in Ready'), ('Custom Build', 'Custom Build'), ('Other', 'Other')], default='Single Family', max_length=100),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_plans', to='projects.project'),
        ),
        migrations.AddField(
            model_name='lot',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='projects.project'),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='lots',
            field=models.ManyToManyField(blank=True, help_text='Available lots for this floor plan', to='projects.lot'),
        ),
        migrations.AddField(
            model_name='rendering',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renderings', to='projects.project'),
        ),
        migrations.AddField(
            model_name='siteplan',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site_plan', to='projects.project'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
