# Generated by Django 5.1.3 on 2025-08-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_floorplan_lot_rendering_siteplan_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lot',
            options={'ordering': ['order', 'lot_number'], 'verbose_name_plural': 'Lots'},
        ),
        migrations.AddField(
            model_name='floorplan',
            name='lot_numbers',
            field=models.TextField(blank=True, help_text='Comma-separated lot numbers this plan is available for'),
        ),
        migrations.AddField(
            model_name='lot',
            name='lot_numbers',
            field=models.TextField(blank=True, help_text='Comma-separated lot numbers (e.g., 1,2,3,4,5)'),
        ),
        migrations.AddField(
            model_name='lot',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
