# Generated by Django 5.1.3 on 2025-08-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_lot_options_floorplan_lot_numbers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='developer',
        ),
        migrations.AlterModelOptions(
            name='floorplan',
            options={'ordering': ['name'], 'verbose_name_plural': 'Floor Plans'},
        ),
        migrations.AlterModelOptions(
            name='rendering',
            options={'ordering': ['title'], 'verbose_name_plural': 'Renderings'},
        ),
        migrations.RemoveField(
            model_name='floorplan',
            name='description',
        ),
        migrations.RemoveField(
            model_name='floorplan',
            name='lot_numbers',
        ),
        migrations.RemoveField(
            model_name='floorplan',
            name='lots',
        ),
        migrations.RemoveField(
            model_name='floorplan',
            name='order',
        ),
        migrations.RemoveField(
            model_name='floorplan',
            name='plan_image',
        ),
        migrations.RemoveField(
            model_name='floorplan',
            name='plan_pdf',
        ),
        migrations.RemoveField(
            model_name='rendering',
            name='order',
        ),
        migrations.RemoveField(
            model_name='siteplan',
            name='description',
        ),
        migrations.RemoveField(
            model_name='siteplan',
            name='image',
        ),
        migrations.RemoveField(
            model_name='siteplan',
            name='pdf',
        ),
        migrations.AddField(
            model_name='floorplan',
            name='plan_file',
            field=models.FileField(blank=True, help_text='Floor plan file (PDF or image)', null=True, upload_to='floor_plans/'),
        ),
        migrations.AddField(
            model_name='lot',
            name='floor_plans',
            field=models.ManyToManyField(blank=True, help_text='Available floor plans for this lot', to='projects.floorplan'),
        ),
        migrations.AddField(
            model_name='lot',
            name='lot_rendering',
            field=models.FileField(blank=True, help_text='Rendering image for this specific lot', upload_to='lot_renderings/'),
        ),
        migrations.AddField(
            model_name='siteplan',
            name='file',
            field=models.FileField(blank=True, help_text='Site plan file (PDF or image)', null=True, upload_to='site_plans/'),
        ),
        migrations.DeleteModel(
            name='Developer',
        ),
    ]
