# Generated by Django 5.1.3 on 2025-08-07 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_remove_project_developer_alter_floorplan_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='area_square_footage',
        ),
        migrations.RemoveField(
            model_name='project',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='project',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='project',
            name='garage_spaces',
        ),
        migrations.RemoveField(
            model_name='project',
            name='lot_size',
        ),
    ]
