# Generated by Django 5.1.3 on 2025-08-08 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_remove_project_area_square_footage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floorplan',
            name='starting_price',
        ),
    ]
