# Generated by Django 5.1.3 on 2025-08-08 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_remove_floorplan_starting_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floorplan',
            name='bathrooms',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='bedrooms',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='garage_spaces',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Number of garage spaces', null=True),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the floor plan', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='square_footage',
            field=models.PositiveIntegerField(blank=True, help_text='Total square footage', null=True),
        ),
    ]
