# Generated by Django 5.1.3 on 2025-08-08 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_floorplan_bathrooms_alter_floorplan_bedrooms_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Projects'},
        ),
    ]
