# Generated by Django 5.1.3 on 2025-08-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='est_completion',
            field=models.DateField(blank=True, help_text='Estimated completion date', null=True),
        ),
    ]
