# Generated by Django 5.1.3 on 2025-08-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_lot_est_completion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='est_completion',
            field=models.CharField(blank=True, default='Spring 2025', help_text="Estimated completion (e.g., 'Spring 2024', 'Q2 2024')", max_length=100),
            preserve_default=False,
        ),
    ]
