# Generated by Django 5.1.3 on 2025-08-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_lot_est_completion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('Recreation', 'Recreation'), ('Fitness', 'Fitness'), ('Community', 'Community'), ('Security', 'Security'), ('Transportation', 'Transportation'), ('Lifestyle', 'Lifestyle'), ('Technology', 'Technology'), ('Environment', 'Environment'), ('Other', 'Other')], default='Other', max_length=50)),
                ('icon', models.CharField(blank=True, help_text='Icon class name or emoji', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Amenities',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='amenities',
            field=models.ManyToManyField(blank=True, help_text='Available amenities for this project', to='projects.amenity'),
        ),
    ]
