# Generated by Django 5.1.3 on 2025-08-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_amenity_project_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='availability_status',
            field=models.CharField(choices=[('Available', 'Available'), ('Reserved', 'Reserved'), ('Sold', 'Sold'), ('Coming Soon', 'Coming Soon'), ('Move In Ready', 'Move In Ready')], default='Available', max_length=20),
        ),
    ]
