# Generated by Django 5.1.3 on 2025-08-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_alter_lot_availability_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['document_type', 'title'], 'verbose_name_plural': 'Documents'},
        ),
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('Document', 'Document & Legal'), ('Marketing Material', 'Marketing Material')], default='Document', max_length=50),
        ),
    ]
