# Generated by Django 5.1.3 on 2025-08-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_alter_document_options_remove_document_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendering',
            name='title',
            field=models.CharField(blank=True, help_text='e.g., Kitchen, Living Room, Exterior', max_length=200),
        ),
    ]
