# Generated by Django 5.1.3 on 2025-08-15 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_alter_contact_name_alter_contact_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFinish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, help_text='e.g., Kitchen, Bathroom, Interior', max_length=100)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features_finishes', to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'Features & Finishes',
                'ordering': ['order', 'category', 'title'],
            },
        ),
    ]
