# Generated by Django 5.1.3 on 2025-08-15 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_featurefinish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featurefinish',
            options={'ordering': ['title'], 'verbose_name_plural': 'Features & Finishes'},
        ),
        migrations.RemoveField(
            model_name='featurefinish',
            name='category',
        ),
        migrations.RemoveField(
            model_name='featurefinish',
            name='description',
        ),
        migrations.RemoveField(
            model_name='featurefinish',
            name='order',
        ),
        migrations.AddField(
            model_name='featurefinish',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='features_finishes/'),
        ),
        migrations.AlterField(
            model_name='featurefinish',
            name='title',
            field=models.CharField(blank=True, help_text='e.g., Kitchen Feature', max_length=200),
        ),
    ]
